version: '3.4'

services:
  hopkins.tech.server:
    image: hopkinstech
    container_name: ${DOCKER_REGISTRY-}hopkinstech
    build:
      context: .
      dockerfile: Server/Dockerfile
    working_dir: /app
    ports: 
      - 3000:443

  db:
    container_name: hopkinstech-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - Server/database.env
    volumes:
      - ./dbdata:/var/opt/mssql/data
    ports:
      - 1433:1433