name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: Server/appsettings.json
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.ConnectionString }}

      - name: Start Containers
        env:
          dbpwd: ${{ secrets.DatabasePassword }}
        run: MSSQL_SA_PASSWORD="$dbpwd" docker-compose up -d
