name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  Deployment:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: appsettings.json Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: Server/appsettings.json
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.ConnectionString }}
          Jwt.TokenSecret: ${{ secrets.TokenSecret }}
          AdminUser.Username: ${{ secrets.AdminUsername }}
          AdminUser.Password: ${{ secrets.AdminPassword }}

      - name: database.env Variable Substitution
        run: sed -i 's/P4ssW0rd!/${{ secrets.DatabasePassword }}/g' Server/database.env

      - name: docker-compose.yml Change Database Path
        run: sed -i 's/.\/dbdata:\/var\/opt\/mssql\/data/..\/..\/..\/..\/dbdata:\/var\/opt\/mssql\/data/g' docker-compose.yml

      - name: Start Containers
        run: docker-compose up -d
